version: 2.1

jobs:
  update-text:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: "git add sample.txt"
      - run: "git commit -m '[CircleCI] update sample.txt'"

workflows:
  update-text:
    jobs:
      - update-text
