version: 2.1

jobs:
  update-text:
    docker:
      - image: ubuntu:xenial-20210804
    steps:
      - checkout 
      - run: apt-get update
      - run: apt-get -y install git 
      - run: git config --global user.email hogehoge
      - run: git config --global user.name tokizuoh
      - run: git add sample.txt
      - run:
          shell: /bin/sh 
          command: |
            set +e
            git commit -m '[CircleCI] update sample.txt'

workflows:
  update-text:
    jobs:
      - update-text
