version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "git log -1"
          command: "git log -1"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
