version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: "git add sample.txt"
      - run: "ls"
      - run: "git commit -m '[CircleCI] update sample.txt'"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
